# NOTE: generated by Claude, not checked yet.

from __future__ import annotations

import numpy as np
import numpy.typing as npt
from py123d.api.scene.scene_filter import AnchorFilterContext
from py123d.api.utils.arrow_metadata_utils import parse_log_directory_metadata
from py123d.datatypes import ModalityType


def has_box_detections(context: AnchorFilterContext) -> npt.NDArray[np.bool_]:
    """
    Whether the log carries a readable box-detections modality.

    Args:
        context: the log's candidate anchors.

    Returns:
        False everywhere when the box-detections modality is missing from the log.
    """
    modality_metadatas = parse_log_directory_metadata(
        context.log_dir,
    ).modality_metadatas
    present = ModalityType.BOX_DETECTIONS_SE3.serialize() in modality_metadatas
    return np.full(len(context.anchors), present, dtype=bool)
