# NOTE: generated by Claude, not checked yet.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, cast

import numpy as np
import numpy.typing as npt
import pyarrow as pa
from py123d.api.scene.arrow.modalities.sync_utils import get_modality_table
from py123d.api.scene.scene_filter import AnchorFilterContext
from py123d.api.utils.arrow_metadata_utils import parse_log_directory_metadata
from py123d.datatypes import ModalityType
from py123d.datatypes.vehicle_state.ego_state_metadata import EgoStateSE3Metadata
from py123d.geometry import EulerAnglesIndex, PoseSE2Index, PoseSE3Index, Vector2D
from py123d.geometry.transform import translate_se2_array_along_body_frame
from py123d.geometry.utils.rotation_utils import get_euler_array_from_quaternion_array


@dataclass(frozen=True)
class EgoFrames:
    """The ego's rear-axle pose and timestamp per sync frame; NaN where the frame carries no ego state."""

    rear_axle_se2_array: npt.NDArray[np.float64]
    timestamps_us: npt.NDArray[np.float64]
    available: npt.NDArray[np.bool_]


def read_ego_frames(context: AnchorFilterContext) -> EgoFrames | None:
    """
    The ego state of every sync frame of the log, as rear-axle SE2 poses.

    Args:
        context: the log's candidate anchors.

    Returns:
        one row per sync frame; None when the log records no ego state.
    """
    ego_key = ModalityType.EGO_STATE_SE3.serialize()
    if ego_key not in context.sync_table.column_names:
        return None
    ego_table = get_modality_table(context.log_dir, ego_key)
    ego_metadata = parse_log_directory_metadata(context.log_dir).modality_metadatas.get(ego_key)
    if ego_table is None or not isinstance(ego_metadata, EgoStateSE3Metadata):
        return None

    pose_column = cast(
        "pa.FixedSizeListArray[Any, Any]",
        ego_table[f"{ego_key}.imu_se3"].combine_chunks(),
    )
    imu_se3_array = cast(
        npt.NDArray[np.float64],
        pose_column.flatten().to_numpy(zero_copy_only=False),  # pyright: ignore[reportUnknownMemberType]
    ).reshape(ego_table.num_rows, len(PoseSE3Index))
    imu_se2_array = np.column_stack(
        [
            imu_se3_array[:, PoseSE3Index.XY],
            get_euler_array_from_quaternion_array(imu_se3_array[:, PoseSE3Index.QUATERNION])[:, EulerAnglesIndex.YAW],
        ],
    )
    rear_axle_to_imu_se2 = ego_metadata.rear_axle_to_imu_se3.pose_se2
    rear_axle_se2_array = translate_se2_array_along_body_frame(
        imu_se2_array,
        Vector2D(rear_axle_to_imu_se2.x, rear_axle_to_imu_se2.y),
    )
    rear_axle_se2_array[:, PoseSE2Index.YAW] += rear_axle_to_imu_se2.yaw
    ego_timestamps_us = cast(
        npt.NDArray[np.int64],
        ego_table[f"{ego_key}.timestamp_us"].to_numpy(),  # pyright: ignore[reportUnknownMemberType]
    )

    rows = cast(
        npt.NDArray[np.float64],
        context.sync_table[ego_key].to_numpy(zero_copy_only=False),  # pyright: ignore[reportUnknownMemberType]
    )
    available = ~np.isnan(rows)
    ego_rows = rows[available].astype(np.int64)
    num_frames = context.sync_table.num_rows
    frame_se2_array = np.full((num_frames, len(PoseSE2Index)), np.nan)
    frame_se2_array[available] = rear_axle_se2_array[ego_rows]
    frame_timestamps_us = np.full(num_frames, np.nan)
    frame_timestamps_us[available] = ego_timestamps_us[ego_rows]
    return EgoFrames(
        rear_axle_se2_array=frame_se2_array,
        timestamps_us=frame_timestamps_us,
        available=available,
    )
