# NOTE: generated by Claude, not checked yet.

from __future__ import annotations

from typing import Final, cast

import numpy as np
import numpy.typing as npt
from py123d.api.scene.arrow.utils.route_utils import (
    ROUTE_POSITION_KEY,
    read_route_position,
)
from py123d.api.scene.scene_filter import AnchorFilterContext
from py123d.geometry import PoseSE2Index

from py123d_garage.py123d_help.scene_filters.filter_fns.ego_frames import read_ego_frames

# Consecutive ego states implying a higher speed are localization jumps, not driving.
_EGO_JUMP_MAX_SPEED_MPS: Final[float] = 55.0


def plausible_ego_motion(context: AnchorFilterContext) -> npt.NDArray[np.bool_]:
    """
    Whether each candidate scene's ego moves at a physically plausible speed.

    Args:
        context: the log's candidate anchors.

    Returns:
        False where any consecutive pair of available ego states within the
        scene's strided frames implies an implausible speed or a non-increasing
        timestamp.
    """
    keep = np.ones(len(context.anchors), dtype=bool)
    ego_frames = read_ego_frames(context)
    if ego_frames is None:
        return keep
    num_frames = context.sync_table.num_rows
    available = ego_frames.available
    positions = ego_frames.rear_axle_se2_array[:, PoseSE2Index.XY]
    times_s = ego_frames.timestamps_us / 1e6

    # A scene's frames are one residue class of the stride; a pair of
    # consecutive available frames in that class is checked by every scene
    # whose window contains it. Implausible pairs sorted by start frame have
    # ascending end frames, so each anchor needs one searchsorted.
    stride = context.stride
    history = context.history_iterations * stride
    future = context.future_iterations * stride
    for residue in range(min(stride, num_frames)):
        of_class = (context.anchors - residue) % stride == 0
        if not of_class.any():
            continue
        frames = np.arange(residue, num_frames, stride, dtype=np.int64)
        present = frames[available[frames]]
        if len(present) < 2:
            continue
        starts, ends = present[:-1], present[1:]
        dt_s = times_s[ends] - times_s[starts]
        distance_m = np.linalg.norm(positions[ends] - positions[starts], axis=1)
        implausible = (dt_s <= 0) | (distance_m > _EGO_JUMP_MAX_SPEED_MPS * dt_s)
        if not implausible.any():
            continue
        bad_starts = starts[implausible]
        bad_ends = np.append(ends[implausible], np.iinfo(np.int64).max)
        anchors = context.anchors[of_class]
        keep[of_class] = bad_ends[np.searchsorted(bad_starts, anchors - history)] > anchors + future
    return keep


# Roads resampled at 1 m turn a few degrees per vertex; a stitched route gap
# meets the real geometry at a near-arbitrary angle.
_ROUTE_MAX_TURN_DEG: Final[float] = 45.0
# Only sharp turns ahead of the anchor corrupt the scene's target points.
_ROUTE_TURN_LOOKAHEAD_M: Final[float] = 60.0


def plausible_route(context: AnchorFilterContext) -> npt.NDArray[np.bool_]:
    """
    Whether the route ahead of each candidate's anchor turns plausibly.

    Args:
        context: the log's candidate anchors.

    Returns:
        False where the route turns implausibly sharply between consecutive
        vertices within the anchor's lookahead window.
    """
    keep = np.ones(len(context.anchors), dtype=bool)
    if ROUTE_POSITION_KEY not in context.sync_table.column_names:
        return keep
    route = read_route_position(context.log_dir)
    if route is None:
        return keep
    route_metadata, progress_by_row, _ = route
    arc = np.asarray(route_metadata.polyline_arc_m, dtype=np.float64)
    xyz = np.asarray(route_metadata.polyline_xyz, dtype=np.float64)
    if len(arc) < 3:
        return keep
    segments = np.diff(xyz[:, :2], axis=0)
    headings = np.arctan2(segments[:, 1], segments[:, 0])
    turns_deg = np.degrees(np.abs(np.angle(np.exp(1j * np.diff(headings)))))
    # turns_deg[i] sits at vertex i + 1.
    sharp_arc_m = arc[1:-1][turns_deg > _ROUTE_MAX_TURN_DEG]
    if len(sharp_arc_m) == 0:
        return keep

    rows = cast(
        npt.NDArray[np.float64],
        context.sync_table[ROUTE_POSITION_KEY].to_numpy(  # pyright: ignore[reportUnknownMemberType]
            zero_copy_only=False,
        ),
    )
    anchor_rows = rows[context.anchors]
    has_progress = ~np.isnan(anchor_rows)
    progress_m = progress_by_row[anchor_rows[has_progress].astype(np.int64)]
    first_sharp = np.searchsorted(sharp_arc_m, progress_m, side="left")
    last_sharp = np.searchsorted(
        sharp_arc_m,
        progress_m + _ROUTE_TURN_LOOKAHEAD_M,
        side="right",
    )
    keep[has_progress] = first_sharp == last_sharp
    return keep
